IG-Website/Controllers/RoutesController.cs
using ApiDataLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace IG_Website.Controllers
{
	public class RoutesController : Controller
	{
		// GET: Routes
		public ActionResult Index()
		{
			return View();
		}
		public ActionResult AllRoutes()
		{
			return View();
		}

		public ActionResult CreateRoute()
		{
			return View();
		}
	}
}

IG-Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - InfiniGuide</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="shortcut icon" type="image/x-icon" href="~/Images/MarkoLogoTransparent.png" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Alegreya:ital@1&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <script src="https://kit.fontawesome.com/6af26a78b2.js" crossorigin="anonymous"></script>

</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				@Html.ActionLink(" ", "AllRoutes", "Routes", new { area = "" }, new { @class = "navbar-brand" })
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Routes", "AllRoutes", "Routes")</li>
					<li>@Html.ActionLink("Create Route", "CreateRoute", "Routes")</li>
					@*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
				</ul>
				@Html.Partial("_LoginPartial")
			</div>
		</div>
	</div>
	<div class="container body-content">
		@RenderBody()
	</div>
	<hr />
	<footer id="footer" class="text-center text-white">
		<div class="container p-4">
			<section class="mb-4" style="margin-top:1.5rem;">
				<!-- Facebook -->
				<a class="btn btn-primary btn-floating m-1 " style="background-color: #3b5998" href="#!" role="button"><i class="fab fa-facebook-f"></i></a>
				<!-- Twitter -->
				<a class="btn btn-primary btn-floating m-1" style="background-color: #55acee" href="#!" role="button"><i class="fab fa-twitter"></i></a>
				<!-- Google -->
				<a class="btn btn-primary btn-floating m-1" style="background-color: #dd4b39" href="#!" role="button"><i class="fab fa-google"></i></a>
				<!-- Instagram -->
				<a class="btn btn-primary btn-floating m-1" style="background-color: #ac2bac" href="#!" role="button"><i class="fab fa-instagram"></i></a>
				<!-- Linkedin -->
				<a class="btn btn-primary btn-floating m-1" style="background-color: #0082ca" href="#!" role="button"><i class="fab fa-linkedin-in"></i></a>
				<!-- Github -->
				<a class="btn btn-primary btn-floating m-1" style="background-color: #333333" href="#!" role="button"><i class="fab fa-github"></i></a>
			</section>
			<section class="">
				<div class="row">
					<div class="col-lg-4 col-md-4 mb-4 mb-md-0">
						@*<h5 class="text-uppercase">Links</h5>*@
						<ul class="list-unstyled mb-0">
							<li>
								@Html.ActionLink("About us", "About", "Home",new { area = "" }, new { @class = "footerLinks" })
							</li>
							<li>
								@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "footerLinks" })
							</li>
							<li>
								@Html.ActionLink("Profile", "Index", "Manage", new { area = "" }, new { @class = "footerLinks" })
							</li>
						</ul>
					</div>
                    <div class="col-lg-4 col-md-4 mb-4 mb-md-0">
                        <img src="~/Images/LogoTrsnpt2.png" alt="avatar" width="250" />
                    </div>
					<div class="col-lg-4 col-md-4 mb-4 mb-md-0">
						@*<h5 class="text-uppercase">Links</h5>*@
                        <ul class="list-unstyled mb-0">
                            <li>
                                @Html.ActionLink("Give us feedback", "AllRoutes", "Routes", new { area = "" }, new { @class = "footerLinks" })
                            </li>
                            <li>
                                @Html.ActionLink("Write a review", "AllRoutes", "Routes", new { area = "" }, new { @class = "footerLinks" })
                            </li>
                        </ul>
					</div>
				</div>
			</section>
		</div>
		<div class="text-center p-3" style="background-color: #fcdab1">
			&copy; @DateTime.Now.Year - InfiniGuide
		</div>
	</footer>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>

</html>